# Generated by Django 6.0.5 on 2026-05-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='highlighted_words',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
